```{r}
library(Seurat)
library(magrittr)
library(dplyr)
library(ggplot2)
library(ggpattern)
library(grid)
library(patchwork)
```

# Load individual Visium samples and corresponding clustering assignment from integrated analysis   

```{r}
metadata = readRDS(file = file.path("..", "..", "analysis_output", "visium_alistair_integrate_cluster.rds"))
sample_abbrs = paste0("SP", 1:8)
obj.list = list()

for (i in 1:length(sample_abbrs)) {
  sample_abbr = sample_abbrs[i]
  barcodes_sample = metadata[metadata$sample == sample_abbr,]$barcode
  cluster_sample = metadata[metadata$sample == sample_abbr,]$seurat_clusters
  
  obj.list[[i]] = readRDS(file.path("..", "..", "analysis_output",  paste0("visium_", sample_abbr,".rds")))
  match_idx = match(rownames(obj.list[[i]]@meta.data), barcodes_sample)
  any(is.na(match_idx))
  obj.list[[i]]$integrate_cluster = cluster_sample[match_idx]
}

```

```{r}
df_all_sample_coords = NULL
for (i in 1:length(sample_abbrs)) {
  sample.sf = obj.list[[i]]@images[[1]]@scale.factors$lowres
  df_all_sample_coords = rbind(df_all_sample_coords,
                               obj.list[[i]]@images[[1]]@coordinates %>%
                                 dplyr::mutate(barcode = row.names(.),
                                               sample = sample_abbrs[i],
                                               sf = sample.sf,
                                               x = imagecol * sample.sf, 
                                               y = -imagerow * sample.sf))
}
df_all_sample_coords = df_all_sample_coords %>%
  dplyr::inner_join(metadata, by = c("sample", "barcode"))
```

```{r}
sample_factor_level = c("SP1", "SP4", "SP7", "SP2", "SP3", "SP8", "SP5", "SP6")
subtype2indices = list()
subtype2indices[["DIF"]] = c(1, 4, 7)
subtype2indices[["IMR"]] = c(5, 6)
subtype2indices[["MES"]] = c(2, 3, 8)
```

# Load cell-cell communication output  

```{r}
df_all_sample_lr = readRDS( 
        file = file.path("..", "intermediate_output", "COMMOT_scaled_lr.rds"))

df_lr_info = readRDS(
        file = file.path("..", "intermediate_output", "COMMOT_lr_info.rds"))
```

```{r}
plot_df_all_sample_lr = df_all_sample_lr %>%
  dplyr::inner_join(df_all_sample_coords, by = c("sample", "barcode")) %>%
  dplyr::mutate(value = ifelse(total.signaling == 0, NA, value))
```

```{r}
all_lrs = unique(df_all_sample_lr$name)
all_lrs = all_lrs[order(all_lrs)]
all_lrs
```

```{r}
cluster.colpal = setNames(c(RColorBrewer::brewer.pal(n = 11, name = "Set3"), "#777777"),
                                 as.character(0:11))
```

# helper function for plotting
```{r}
tab_to_geom_tile <- function(tab, 
                             border_col = "black",
                             x_lab = "",
                             y_lab = "",
                             y_axis_on_right = T,
                             show_x_text = T,
                             show_y_text = T,
                             breaks = seq(from=-1,to=1,by=0.05),
                             colpal = colorRampPalette(rev(RColorBrewer::brewer.pal(n = 7, name = "RdBu")))(length(breaks) - 1),
                             break_labels = as.character(breaks),
                             limits = c(breaks[1], breaks[length(breaks)]),
                             guide_name = "x",
                             show_guide = F) {
  
  tab[tab > limits[2]] = limits[2]
  tab[tab < limits[1]] = limits[1]
  x = names(dimnames(tab))[2]
  y = names(dimnames(tab))[1]
  
  as.data.frame.table(as.matrix(tab), responseName = "fill") %>%
  ggplot(aes(x = .data[[x]], y = .data[[y]], fill = fill)) +
  geom_tile(color = border_col) +
    labs(x = "cluster") +
    scale_y_discrete(position = ifelse(y_axis_on_right, "right", "left")) + 
    scale_fill_gradientn(
      breaks = breaks,
      colours = colpal,
      labels = break_labels,
      limits = limits,
      name = guide_name,
    ) +
    labs(x=x_lab, y=y_lab) + 
    theme_minimal() +
    theme(axis.title.y = element_text(size=6),
          axis.title.x = element_text(size=6),
          legend.position = ifelse(show_guide, "right", "none")
          ) + 
    guides(fill = guide_colorbar(
      draw.ulim = FALSE,
      draw.llim = FALSE, 
      ticks = FALSE))
  
}

```

```{r}
lr_df_to_geom_violin <- function(df,
                                 lr,
                                 s,
                                 x_lab = "",
                                 y_lab = "",
                                 y_axis_on_right = T,
                                 show_x_text = T,
                                 show_y_text = T,
                                 ylims = c(0, 25),
                                 stat_fun = function(x) mean(x, na.rm=T),
                                 breaks = seq(from = 0, to = 5, by = 0.5),
                                 colpal = colorRampPalette(RColorBrewer::brewer.pal(n = 7, name = "Reds"))(length(breaks) - 1),
                                 break_labels = as.character(breaks),
                                 limits = c(breaks[1], breaks[length(breaks)]),
                                 guide_name = "",
                                 guide_pos = "none") {
  df %>%
    dplyr::filter(name == lr,
                  sample == s) %>%
    dplyr::group_by(seurat_clusters) %>%
    dplyr::mutate(stat_signal = min(stat_fun(value), limits[2])) %>%
    ggplot(aes(x = seurat_clusters, y = value, fill = stat_signal)) + 
    scale_x_discrete(drop=FALSE) +
    geom_violin(scale = "width") +
    ylim(ylims[1], ylims[2]) +
    labs(y = y_lab, x =  x_lab) +
    theme_minimal() +
    scale_fill_gradientn(
      breaks = breaks,
      colours = colpal,
      labels = break_labels,
      limits = limits,
      name = guide_name,
    ) +
    guides(fill = guide_colorbar(
      draw.ulim = FALSE,
      draw.llim = FALSE,
      ticks = FALSE
    )) +
    theme(axis.title.y = element_text(size=6),
          axis.title.x = element_text(size=6),
          legend.position = guide_pos)
}

```

# differ by signal strength
```{r,message=F,warning=F}
min.spot.n = 50
signal.breaks = c(0, 1, 5, 10, 100)
signal.bin.labels = c("<1%", "1-5%", "5-10%", ">10%")

violin.breaks = seq(from = 0, to = 15, by = 1)
violin.colpal =
  colorRampPalette((RColorBrewer::brewer.pal(n = 7, name = "Reds")))(length(violin.breaks) - 1)
violin.labels = as.character(violin.breaks)
violin.labels[!violin.breaks %in% c("0", "5", "10", "15")] = ""
violin.limits = c(violin.breaks[1], violin.breaks[length(violin.breaks)])
violin.guide.name = "75th percentile signal"

chi.breaks = seq(from = -1,
                     to = 1,
                     by = 0.05)
chi.colpal =
  colorRampPalette(rev(RColorBrewer::brewer.pal(n = 7, name = "RdBu")))(length(chi.breaks) - 1)
chi.labels = as.character(chi.breaks)
chi.labels[!chi.labels %in% as.character(c(-1, -0.5, 0, 0.5, 1))] = ""
chi.limits = c(-1, 1)
chi.name = "(obs-exp)/exp"

plt.pt.size = 0.6
spatial.breaks = c(-1, 0, 1, 5, 10, 100)

spatial.colpal = setNames(c("white", "#FEE5D9", "#FC9F81", "#F1553E"),
                          signal.bin.labels)

lrs_select = c(
  "MDK.SDC1",
  "MDK.SDC4",
  "MIF.CD74_CXCR4",
  "MIF.CD74_CD44",
  "PTN.SDC1",
  "PTN.NCL",
  "SPP1.CD44",
  "SPP1.ITGAV_ITGB1",
  "TNFSF12.TNFRSF12A",
  "PDGFC.PDGFRA"
)

patch.list = list()

subtype = "DIF"
  
for (lr in lrs_select) {
  col.label.grob.list = list()
  summary.violin.plot.list = list()
  summary.chi.plot.list = list()
  spatial.plot.list = list()
  
  for (s in sample_abbrs[subtype2indices[[subtype]]]) {
    col.label.grob.list[[s]] =
      wrap_elements(panel = textGrob(s, 
                                     rot = 0,
                                     gp = gpar(fontsize = 8)))
    
    df_binned = plot_df_all_sample_lr %>%
      dplyr::filter(name == lr,
                    sample == s) %>%
      dplyr::mutate(
        signal.bin =
          cut(
            value,
            breaks = signal.breaks,
            labels = signal.bin.labels,
            right = F,
            include.lowest = T
          ),
        signal.bin = factor(signal.bin, levels = rev(signal.bin.labels))
      )
    
    cont_table = table(df_binned[, c("signal.bin", "seurat_clusters")])
    filter_mask = apply(cont_table, 2, sum) < min.spot.n
    
    cont_table[, filter_mask] = 0
    exp_table = (chisq.test(cont_table))$expected
    cont_table[, filter_mask] = NA
    chi_table = (cont_table - exp_table) / exp_table
    cont_table_prop = prop.table(cont_table, margin = 2)
    cont_table_prop[, filter_mask] = NA
    
    summary.violin.plot.list[[s]] = lr_df_to_geom_violin(
      plot_df_all_sample_lr,
      lr = lr,
      s = s,
      x_lab = "",
      y_lab = "% signal",
      stat_fun = function(x)
        quantile(x, probs = 0.75, na.rm = T),
      breaks = violin.breaks,
      colpal = violin.colpal,
      break_labels = violin.labels,
      guide_name = violin.guide.name,
      guide_pos = "none"
    ) + theme(axis.text.y = element_text(size = 6),
              axis.text.x = element_blank())
    
    summary.chi.plot.list[[s]] = tab_to_geom_tile(
      chi_table[rev(rownames(chi_table)), ],
      x_lab = "",
      y_lab = "binned % signal",
      y_axis_on_right = F,
      breaks = chi.breaks,
      colpal = chi.colpal,
      break_labels = chi.labels,
      limits = chi.limits,
      guide_name = chi.name
    ) + theme(axis.text.y = element_text(size = 6),
              axis.text.x = element_text(size = 6))
    
    spatial.plot.list[[s]] = df_binned %>%
      ggplot(aes(
        x = x,
        y = y,
        fill = signal.bin,
        color = seurat_clusters,
      )) +
      ggstar::geom_star(starshape = 6,
                        size = plt.pt.size,
                        starstroke = 0.10) +
      ylim(c(-600, 0)) + xlim(0, 600) +
      coord_fixed() +
      theme_void() +
      theme(
        legend.position = "bottom",
        legend.direction = "horizontal",
        plot.title = element_text(hjust = 0.5)
      ) +
      scale_y_continuous(position = "right") +
      scale_fill_manual(values = spatial.colpal,
                        name = "Scaled signaling",
                        drop = F) +
      scale_color_manual(values = cluster.colpal,
                         name = "Cluster",
                         drop = F)  +
      guides(
        fill = guide_legend(override.aes = list(size = 2),
                            nrow = 1),
        colour = guide_legend(
          override.aes = list(size = 2, starstroke = 0.5),
          nrow = 1
        )
      ) +
      theme(
        legend.text = element_text(size = 5),
        legend.title = element_text(size = 8),
        legend.position = "none"
      ) + 
         theme(plot.margin = unit(rep(-20, 4), "points")) 
  }
  
  patch.list[[lr]] = patchworkGrob(wrap_plots(
    c(
      col.label.grob.list,
      summary.violin.plot.list,
      summary.chi.plot.list,
      sapply(spatial.plot.list, 
             FUN = function(x) ggplotify::as.grob(x),
             simplify = F)
    )
  ) +
    plot_layout(
      ncol = length(subtype2indices[[subtype]]),
      byrow = T,
      heights = c(0.1, 1, 0.5, 3)
    ) + 
    plot_annotation(title = lr,
                    theme = theme(plot.title = element_text(hjust = 0.5))
                    )
  )
}

```

```{r}
p = wrap_plots(patch.list) + 
  plot_layout(ncol = 2) + 
  plot_annotation(tag_levels = "A", tag_suffix = "") &
    theme(plot.tag = element_text(face = 'bold',
                                  size = 40))

ggsave(
    filename = "main_fig_5.png",
    plot  = p,
    path = file.path("."),
    width = 18,
    height = 22,
    units = "in",
    dpi = 330,
    limitsize = F,
    bg = "white"
  )
```

```{r, warning=F, message=F}
dummy.violin = 
  data.frame(seurat_clusters = c("0", "1"), 
             stat_signal = c(0, 100),
             value = c(0, 100)
             )%>%
    ggplot(aes(x = seurat_clusters, y = value, fill = stat_signal)) +
    geom_violin(scale = "width") +
    labs(y = "", x =  "") +
    theme_void() +
    scale_fill_gradientn(
      breaks = violin.breaks,
      colours = violin.colpal,
      labels = violin.labels,
      limits = violin.limits,
      name = "cluster mean signal"
    ) +
    guides(fill = guide_colorbar(
      draw.ulim = FALSE,
      draw.llim = FALSE,
      ticks = FALSE
    )) 
violin.legend = ggpubr::get_legend(dummy.violin)
violin.legend = ggpubr::as_ggplot(violin.legend)
violin.legend
```

```{r, warning=F, message=F}
dummy.chi.plot = data.frame(a = c(0,1),
           b = c(0,1),
           f = c(-1, 1)
             ) %>%
  ggplot(aes(x = a, y = b, fill = f)) +
  geom_tile() +
    scale_fill_gradientn(
      breaks = chi.breaks,
      colours = chi.colpal,
      labels = chi.labels,
      limits = chi.limits,
      name = chi.name,
    ) +
    labs(x="", y="") + 
    theme_void() +
    theme(
          legend.position = "right"
          ) + 
    guides(fill = guide_colorbar(
      draw.ulim = FALSE,
      draw.llim = FALSE, 
      ticks = FALSE))

chi.plot.legend = ggpubr::get_legend(dummy.chi.plot)
chi.plot.legend = ggpubr::as_ggplot(chi.plot.legend)
chi.plot.legend
```

```{r, warning=F, message=F}
dummy.spatial = 
  data.frame(x = c(0, 1), 
             y = c(0, 1),
             value = c(0, 100)
             ) %>%
        dplyr::mutate(
          signal.bin =
            cut(
              value,
              breaks = signal.breaks,
              labels = signal.bin.labels,
              right = F,
              include.lowest = T
            ),
          signal.bin = factor(signal.bin, levels = rev(signal.bin.labels))
        ) %>%
        ggplot(aes(
          x = x,
          y = y,
          fill = signal.bin
        )) +
        ggstar::geom_star(starshape = 6,
                          size = plt.pt.size,
                          starstroke = 0.00) +
        scale_fill_manual(values = signal.colpal,
                          name = "Scaled signaling",
                          drop = F) + 
  guides(fill = guide_legend(override.aes = list(size = 5)))

sp.plot.legend = ggpubr::get_legend(dummy.spatial)
sp.plot.legend = ggpubr::as_ggplot(sp.plot.legend)
sp.plot.legend
```
